### PR TITLE
Implement early stopping

### PR DESCRIPTION
**Pull request by klieret**

### CODE REVIEW

**Comment by GageDeZoort** [comment]
The \min_\delta formulation of early stopping might be tough for us here because we'll be trying different minimization schemes, e.g. dynamic weights attached to each term in the loss function. Maybe we should instead ask for a percent change in loss across the previous N epochs?

**Comment by klieret** [comment]
Yes, let me do this a bit more general then.

**Comment by klieret** [comment]
Actually ray tune also implements early stopping, so maybe let's hold off on merging this one if we go with ray tune

**Comment by klieret** [comment]
I think we will now move to having this handled by ray tune, so I will close this.

**Pull request closed without merging**
